# Generated by Django 5.2.11 on 2026-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0005_shipment_shippingrate_webhooklog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('corporate', 'Corporate Gifting'), ('employee', 'Employee Appreciation'), ('client', 'Client Gifting'), ('event', 'Corporate Event'), ('wedding', 'Wedding Bulk Order'), ('festival', 'Festival Gifting'), ('other', 'Other')], default='corporate', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Minimum 50 pieces')),
                ('product_interest', models.TextField(help_text="Describe the products you're interested in")),
                ('budget_range', models.CharField(blank=True, help_text='e.g., ₹50,000 - ₹1,00,000', max_length=100)),
                ('delivery_timeline', models.CharField(blank=True, help_text='When do you need delivery?', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Any additional requirements or customization needs')),
                ('gst_number', models.CharField(blank=True, help_text='GST Number (optional)', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('converted', 'Converted to Order'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for follow-up')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Inquiry',
                'verbose_name_plural': 'Bulk Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
