# Generated by Django 5.2.11 on 2026-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0008_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonepe_merchant_transaction_id',
            field=models.CharField(blank=True, help_text='PhonePe merchant transaction ID', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_payment_instrument',
            field=models.CharField(blank=True, help_text='Payment method used (UPI, CARD, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_response_code',
            field=models.CharField(blank=True, help_text='PhonePe response code', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, help_text='PhonePe transaction ID', max_length=200),
        ),
    ]
