# Generated by Django 5.2.11 on 2026-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0009_add_phonepe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, related_name='products', to='gift.occasion'),
        ),
    ]
