# Generated by Django 6.0.1 on 2026-01-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_alter_address_options_alter_returnrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_session_cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
