# Generated by Django 5.2.11 on 2026-02-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_remove_cart_unique_session_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(help_text='Shiprocket order ID', max_length=50, unique=True)),
                ('shiprocket_shipment_id', models.CharField(blank=True, help_text='Shiprocket shipment ID', max_length=50)),
                ('awb_code', models.CharField(blank=True, db_index=True, help_text='Air Waybill tracking number', max_length=50)),
                ('courier_id', models.IntegerField(blank=True, help_text='Shiprocket courier company ID', null=True)),
                ('courier_name', models.CharField(blank=True, help_text='Courier company name', max_length=100)),
                ('pickup_scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled pickup date and time', null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated delivery date', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual delivery date and time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready_to_ship', 'Ready to Ship'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rto', 'Return to Origin')], default='pending', help_text='Current shipment status', max_length=50)),
                ('current_status', models.CharField(blank=True, help_text='Detailed status from courier', max_length=100)),
                ('label_url', models.URLField(blank=True, help_text='Shipping label PDF URL')),
                ('manifest_url', models.URLField(blank=True, help_text='Manifest PDF URL')),
                ('invoice_url', models.URLField(blank=True, help_text='Invoice PDF URL')),
                ('last_tracking_update', models.DateTimeField(blank=True, help_text='Last time tracking was updated', null=True)),
                ('tracking_data', models.JSONField(blank=True, default=dict, help_text='Complete tracking history')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', help_text='Sync status with Shiprocket', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of sync retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_pincode', models.CharField(help_text='Pickup pincode', max_length=10)),
                ('delivery_pincode', models.CharField(help_text='Delivery pincode', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Package weight in kg', max_digits=8)),
                ('courier_id', models.IntegerField(help_text='Shiprocket courier company ID')),
                ('courier_name', models.CharField(help_text='Courier company name', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Shipping rate in INR', max_digits=10)),
                ('estimated_delivery_days', models.IntegerField(help_text='Estimated delivery time in days')),
                ('cod_available', models.BooleanField(default=False, help_text='Cash on Delivery available')),
                ('rating', models.FloatField(default=0.0, help_text='Courier rating')),
                ('cached_at', models.DateTimeField(auto_now=True, help_text='When this rate was cached')),
                ('expires_at', models.DateTimeField(help_text='When this cache expires')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=50)),
                ('payload', models.JSONField(help_text='Complete webhook payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether webhook was processed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('order_id', models.CharField(blank=True, help_text='Related order ID if applicable', max_length=50)),
                ('awb_code', models.CharField(blank=True, help_text='Related AWB code if applicable', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When webhook was received')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.IntegerField(blank=True, help_text='Selected courier ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync failed'),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_synced',
            field=models.BooleanField(default=False, help_text='Order synced to Shiprocket'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='gift.order'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['pickup_pincode', 'delivery_pincode', 'weight'], name='gift_shippi_pickup__d1dc39_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['expires_at'], name='gift_shippi_expires_675711_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['event_type'], name='gift_webhoo_event_t_56c5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['processed'], name='gift_webhoo_process_957bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['order_id'], name='gift_webhoo_order_i_8a8830_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['awb_code'], name='gift_webhoo_awb_cod_71147b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['created_at'], name='gift_webhoo_created_fc2c25_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['awb_code'], name='gift_shipme_awb_cod_53a488_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='gift_shipme_status_fa5deb_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sync_status'], name='gift_shipme_sync_st_5a2c90_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='gift_shipme_created_7a2570_idx'),
        ),
    ]
